### ISSUE TITLE
Column width on large screens

### ISSUE THREAD

**Issue by sdicke** [chaossocial/custom#11]
On large screens (I tried it on al 27" screen) the columns are very wide. There would be place for more columns, but obviously the column count is limited. I do not know if it could be fixed with a layout or if there (lacking?) support by the Mastodon software would be needed.

**Comment by rixx** [comment]
Two questions:

Does switching to the default Mastodon theme solve the issue for you? (In that case, our version might just not be a good fit for you)


What do you mean by "obviously the column count is limited" - I'm not aware of an upper limit placed by Mastodon on the column count. How high is this limit, that it is a problem for you? This is definitely something you could file with the Mastodon project to remove, I can imagine that an upper column limit is problematic for many people (but I can't speak to that because I haven't managed to hit it yet).
